### ISSUE TITLE
Pretrained model link broken

### ISSUE THREAD

**Issue by coallaoh** [prlz77/ResNeXt.pytorch#11]
In the README, link to the CIFAR trained models (https://mega.nz/#F!wbJXDS6b!YN3hCDi1tT3SdNFrLPm7mA) is broken. Can you check and share the pretrained models?

Thanks :)

**Comment by prlz77** [comment]
Hi! 

It works for me! can you try on another computer network?

Btw, you'll have to revert to a previous version of the code in this repo to make them work (it is written in the README). Whenever I have some GPUs available I will retrain them with the latest code. Or, if you have the resources I'd really appreciate if you could train and send me the model.

Pau

**Comment by coallaoh** [comment]
I see - it's not broken. In a new wireless network the download works fine.
Thanks for the instructions. I'm not sure if I'll train the model myself, but if I do I'll surely send you the weights ;)

**Comment by iamZe** [comment]
the link seems not working

**Comment by prlz77** [comment]
Did you read the last comments? Did you try in another network?
