### ISSUE TITLE
Can I directly convert TensorFlow's ResNext weight to pytorch's weight and use it directly?

### ISSUE THREAD

**Issue by ma3252788** [prlz77/ResNeXt.pytorch#20]
Can I directly convert TensorFlow's ResNext weight to pytorch's weight and use it directly?

Or, do you have a pre-trained model on a large data set?

**Comment by prlz77** [comment]
Not directly, you will have to find the corresponding Pytorch weight matrix to fill with each weight matrix from TF. However, it is not impossible. If you do it, I'd be happy to incorporate it here through a pull request.

**Comment by ma3252788** [comment]
> Not directly, you will have to find the corresponding Pytorch weight matrix to fill with each weight matrix from TF. However, it is not impossible. If you do it, I'd be happy to incorporate it here through a pull request.



OK, I will try~Thank you !
