### ISSUE TITLE
question about the dimension of the net

### ISSUE THREAD

**Issue by Agito555** [prlz77/ResNeXt.pytorch#21]
If the input of the net is of 64*3*224*224 dimension,where 64 is the batch size,3 is the channels and 224 is the size of the original image,and i run the code and find out that the output's dimension of the net is 4802*10,where 10 is the classes to predict.
Is the output correct?Shouldn't the dimension of the output be 64*10?
Maybe i get something wrong?

**Comment by Agito555** [comment]
If the input of the net is of 64*3*224*224 dimension,where 64 is the batch size,3 is the channels and 224 is the size of the original image,and i run the code and find out that the output's dimension of the net is 4802*10,where 10 is the classes to predict.
Is the output correct?Shouldn't the dimension of the output be 64*10?
Maybe i get something wrong?

**Comment by Agito555** [comment]
If the input of the net is of 64x3x224x224 dimension,where 64 is the batch size,3 is the channels and 224 is the size of the original image,and i run the code and find out that the output's dimension of the net is 4802x10,where 10 is the classes to predict.
Is the output correct?Shouldn't the dimension of the output be 64x10?
Maybe i get something wrong?

**Comment by prlz77** [comment]
Hi @Agito555 the problem is that the network expects images of size 32, so inputting 224 results in bigger feature maps, which messes up with the average pooling https://github.com/prlz77/ResNeXt.pytorch/blob/master/models/model.py#L138

I suggest you just change the above line by x.mean((2,3))

Hope this helps!

Pau

**Comment by Agito555** [comment]
Yeah,thanks for your reply. I take it for granted that the input size of the image is the same as the size in the paper.
I also want to know whether the network architecture is a little bit different from the architecture(Resnext50) in the paper?

**Comment by prlz77** [comment]
Well in the paper they also try CIFAR ([Table 7](https://arxiv.org/pdf/1611.05431.pdf)) for which the input is 32x32. There should be no differences with respect to the CIFAR model. If there are, it could be due to many reasons such as differences in the frameworks used to train the models.
